version: '3.8'

services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
      - mnist_data:/app/mnist
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''

volumes:
  mnist_data:  # Persistent volume for MNIST data